# Generated by Django 4.1.1 on 2022-09-22 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('ceo_name', models.CharField(max_length=50, verbose_name='Ceo Name')),
                ('address', models.TextField()),
                ('inception_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_lead', models.CharField(max_length=100, verbose_name='Team Lead Name')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='api.company')),
            ],
        ),
    ]
