# Generated by Django 4.1.1 on 2022-09-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_company_options_alter_team_company_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="team_lead",
            new_name="team_lead_name",
        ),
    ]
