# Generated by Django 4.1.1 on 2022-09-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_team_lead_team_team_lead_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("name", "ceo_name")},
        ),
    ]
